// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaRH.Data;

#nullable disable

namespace SistemaRH.Data.Migrations
{
    [DbContext(typeof(RhDbContext))]
    [Migration("20260702034725_RenomearEmailAgilEAdicionarComplemento")]
    partial class RenomearEmailAgilEAdicionarComplemento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SistemaRH.Domain.Entities.Atestado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Arquivo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Cid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtestado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasFaltados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId", "DataInicio", "DataFim");

                    b.ToTable("Atestados");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.ContratoPJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioPJId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorasMensais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RpaBrancoConhecimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoContrato")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorFixo")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorHora")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorProjeto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FuncionarioPJId");

                    b.ToTable("ContratosPJ");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Ferias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaRenovacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasDisponiveis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasNaoRemunerados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasRemunerados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasUtilizados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AjudaDeCusto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Comissionado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contratante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosBancarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAgil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ramal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoFuncionario")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.HasIndex("EmpresaId", "Tipo");

                    b.ToTable("Funcionarios");

                    b.HasDiscriminator<int>("TipoFuncionario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoresAntes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoresDepois")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.PeriodoFerias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeriasId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Remunerada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FeriasId");

                    b.ToTable("PeriodosFerias");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.RpaNfPJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Arquivo")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ContratoPJId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoServico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuncionarioPJId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorDescontos")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContratoPJId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FuncionarioPJId");

                    b.HasIndex("StatusPagamento");

                    b.HasIndex("Mes", "Ano");

                    b.ToTable("RpasNfsPJ");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.SalarioHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVigencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescontoINSS")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescontoIRPF")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescontoOutros")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalarioLiquido")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("SalarioHistorico");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.FuncionarioCLT", b =>
                {
                    b.HasBaseType("SistemaRH.Domain.Entities.Funcionario");

                    b.Property<decimal>("AuxilioEducacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cargo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Codigo");

                    b.Property<decimal>("ComplementoSalarial")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("ComplementoSalarial");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cpf");

                    b.Property<string>("Ctps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdmissao")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataAdmissao");

                    b.Property<DateTime?>("DataDemissao")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataDemissao");

                    b.Property<DateTime>("DataNascimento")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Departamento");

                    b.Property<string>("PisPassep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Rg");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.FuncionarioEstagiario", b =>
                {
                    b.HasBaseType("SistemaRH.Domain.Entities.Funcionario");

                    b.Property<decimal>("Bolsa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cargo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Codigo");

                    b.Property<decimal>("ComplementoSalarial")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("ComplementoSalarial");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("DataAdmissao")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataAdmissao");

                    b.Property<DateTime?>("DataDemissao")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataDemissao");

                    b.Property<DateTime>("DataNascimento")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Departamento");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Rg");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.FuncionarioPJ", b =>
                {
                    b.HasBaseType("SistemaRH.Domain.Entities.Funcionario");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("Departamento");

                    b.Property<string>("DiaSolicitacaoNF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmiteNF")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FeriasRemuneradas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneAgil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TemDireitoFerias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidadeContrato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorContratado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorServico")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Atestado", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany("Atestados")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.ContratoPJ", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRH.Domain.Entities.FuncionarioPJ", "FuncionarioPJ")
                        .WithMany("Contratos")
                        .HasForeignKey("FuncionarioPJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("FuncionarioPJ");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Ferias", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.Funcionario", "Funcionario")
                        .WithOne("Ferias")
                        .HasForeignKey("SistemaRH.Domain.Entities.Ferias", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Funcionario", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.PeriodoFerias", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.Ferias", "Ferias")
                        .WithMany("Periodos")
                        .HasForeignKey("FeriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ferias");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.RpaNfPJ", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.ContratoPJ", "Contrato")
                        .WithMany("RpasNfs")
                        .HasForeignKey("ContratoPJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRH.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaRH.Domain.Entities.FuncionarioPJ", "FuncionarioPJ")
                        .WithMany("RpasNfs")
                        .HasForeignKey("FuncionarioPJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Empresa");

                    b.Navigation("FuncionarioPJ");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.SalarioHistorico", b =>
                {
                    b.HasOne("SistemaRH.Domain.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.ContratoPJ", b =>
                {
                    b.Navigation("RpasNfs");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Ferias", b =>
                {
                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("Atestados");

                    b.Navigation("Ferias")
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRH.Domain.Entities.FuncionarioPJ", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("RpasNfs");
                });
#pragma warning restore 612, 618
        }
    }
}
